# Generated by Django 6.0.7 on 2026-07-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='held_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'held_until'], name='reservation_status_3760b8_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_date', 'reservation_time', 'status'], name='reservation_reserva_e6dddf_idx'),
        ),
    ]
