# Generated by Django 6.0.7 on 2026-07-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('customer_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('preferred_cuisine', models.CharField(blank=True, default='', max_length=255)),
                ('dietary_restrictions', models.CharField(blank=True, default='', max_length=500)),
                ('spice_tolerance', models.CharField(blank=True, default='', max_length=50)),
                ('budget_range', models.CharField(blank=True, default='', max_length=100)),
                ('favorite_items', models.TextField(blank=True, default='')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_reservations', models.IntegerField(default=0)),
                ('avg_spend', models.FloatField(default=0)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('last_reservation_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EpisodicMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=255)),
                ('conversation_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('event_data', models.JSONField(default=dict)),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('tool_success', models.BooleanField(blank=True, null=True)),
                ('tool_duration_ms', models.IntegerField(blank=True, null=True)),
                ('user_message', models.TextField(blank=True, null=True)),
                ('assistant_response', models.TextField(blank=True, null=True)),
                ('goal_description', models.CharField(blank=True, max_length=500, null=True)),
                ('goal_status', models.CharField(blank=True, max_length=50, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('outcome', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id', 'conversation_id'], name='agent_episo_custome_a49266_idx'), models.Index(fields=['event_type', 'created_at'], name='agent_episo_event_t_7c457b_idx'), models.Index(fields=['tool_name', 'tool_success'], name='agent_episo_tool_na_1464d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SemanticMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('fact_key', models.CharField(max_length=255)),
                ('fact_value', models.TextField()),
                ('confidence', models.FloatField(default=0.5)),
                ('observation_count', models.IntegerField(default=1)),
                ('source_conversation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source_tool', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_observed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_observed_at'],
                'indexes': [models.Index(fields=['customer_id', 'category'], name='agent_seman_custome_0c47a2_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer_id', 'category', 'fact_key'), name='unique_customer_category_fact_key')],
            },
        ),
    ]
