# Generated by Django 6.0.7 on 2026-07-14 08:09
# Modified: VectorExtension + IvfflatIndex only run on PostgreSQL.
# On SQLite (testing), they are skipped via SeparateDatabaseAndState.
# This ensures tests can run on SQLite without pgvector errors.

from django.conf import settings
from django.db import migrations, models
from pgvector.django import IvfflatIndex, VectorField


def _is_pg():
    return "postgresql" in settings.DATABASES["default"]["ENGINE"]


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        # Create the table WITHOUT the IvfflatIndex (added conditionally below)
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_type", models.CharField(choices=[("menu_item", "Menu Item"), ("policy", "Restaurant Policy"), ("faq", "FAQ"), ("promotion", "Promotion")], db_index=True, max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("embedding", VectorField(dimensions=1536)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["content_type", "title"],
            },
        ),
    ]


# ── PostgreSQL-only operations ──────────────────────────────────────────
# Add the pgvector extension and the IvfflatIndex, but only when running
# on PostgreSQL. On SQLite (test mode), we update Django's state so it
# doesn't detect a mismatch, but skip the actual DDL.

if _is_pg():
    # Create pgvector extension before creating the IvfflatIndex
    Migration.operations.insert(0, migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector", reverse_sql="", state_operations=[]))
    # Add the IvfflatIndex on PostgreSQL
    Migration.operations.append(
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="knowledgebase",
                    index=IvfflatIndex(
                        name="knowledge_embedding_idx",
                        fields=["embedding"],
                        opclasses=["vector_l2_ops"],
                        lists=100,
                    ),
                ),
            ],
            database_operations=[
                migrations.AddIndex(
                    model_name="knowledgebase",
                    index=IvfflatIndex(
                        name="knowledge_embedding_idx",
                        fields=["embedding"],
                        opclasses=["vector_l2_ops"],
                        lists=100,
                    ),
                ),
            ],
        )
    )
else:
    # On SQLite: only update Django's state (no actual DDL).
    # This keeps the migration state consistent with the model's Meta.indexes
    # so 'makemigrations' won't regenerate this migration.
    Migration.operations.append(
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="knowledgebase",
                    index=IvfflatIndex(
                        name="knowledge_embedding_idx",
                        fields=["embedding"],
                        opclasses=["vector_l2_ops"],
                        lists=100,
                    ),
                ),
            ],
            database_operations=[],
        )
    )
