# Generated by Django 6.0.7 on 2026-07-14 08:09

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('menu_item', 'Menu Item'), ('policy', 'Restaurant Policy'), ('faq', 'FAQ'), ('promotion', 'Promotion')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['content_type', 'title'],
                'indexes': [pgvector.django.indexes.IvfflatIndex(name='knowledge_embedding_idx', fields=['embedding'], opclasses=['vector_l2_ops'], lists=100)],
            },
        ),
    ]
