# Generated by Django 6.0.7 on 2026-07-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='chapa_tx_ref',
            field=models.CharField(blank=True, default='', help_text='Chapa transaction reference for verification', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, default='', help_text='Chapa checkout URL for user redirect', max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='ETB', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('chapa', 'Chapa'), ('telebirr', 'Telebirr'), ('cbe_birr', 'CBE Birr'), ('card', 'Card'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
