# Generated by Django 6.0.7 on 2026-07-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('spicy', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('allergens', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
